export type NameType = {
  id: string, nameStr: string, type: 'name'| 'singleName' | 'family'
}

export const guestList: NameType[]= [
  {id: 'guest', nameStr: 'Дорогой гость', type: 'singleName'},
  {id: 'parents', nameStr: 'папа и мама', type: 'name'},
  {id: 'mkartychev-kh', nameStr: 'Мкартычева Хачатура', type: 'family'},
  {id: 'mkartychev-v', nameStr: 'Мкартычева Виталия', type: 'family'},
  {id: 'arutyunov-oa', nameStr: 'Арутюнова Ованеса', type: 'family'},
  {id: 'ovsepyan-a', nameStr: 'Арестак, Рубик и Людочка', type: 'name'},
  {id: 'lyudmila', nameStr: 'Дорогая Людочка', type: 'singleName'},
  {id: 'ovsepyan-d', nameStr: 'Давид, Рубен и Левон', type: 'name'},
  {id: 'karapetyan-l', nameStr: 'Карапетяна Левона', type: 'family'},
  {id: 'karapetyan-a', nameStr: 'Дорогая Карапетян Альвина', type: 'singleName'},
  {id: 'mykyrtychev', nameStr: 'Нуна и Артём', type: 'name'},
  {id: 'iskander-diana', nameStr: 'Искандер и Диана', type: 'name'},
  {id: 'arkady-angela', nameStr: 'Аркадий и Анжела', type: 'name'},
  {id: 'kirakosovs', nameStr: 'Киракосовых', type: 'family'},
  {id: 'alla', nameStr: 'Дорогая Алла', type: 'singleName'},
  {id: 'karapetyan-g', nameStr: 'Карапетяна Геворка', type: 'family'},
  {id: 'karapetovs', nameStr: 'Карапетовых', type: 'family'},
  {id: 'angela-raphael', nameStr: 'Анжела и Рафик', type: 'name'},
  {id: 'karapetyan-ar', nameStr: 'Карапетян', type: 'family'},
  {id: 'jeanne', nameStr: 'Дорогая Малхазова Жанна', type: 'singleName'},
  {id: 'egoyan-e', nameStr: 'Егояна Эдуарда', type: 'family'},
  {id: 'egoyan-a', nameStr: 'Егояна Алика', type: 'family'},
  {id: 'grigoryan', nameStr: 'Григоряна Арменака', type: 'family'},
  {id: 'arzumanyan', nameStr: 'Арзуманян Армен и Светлана', type: 'name'},
  {id: '25', nameStr: 'Сергей, Лилия, Альберт и Армине', type: 'name'},
  {id: '26', nameStr: 'Лаура, Рудольф, Кристина, Артур и Дарина', type: 'name'},
  {id: '27', nameStr: 'Лиана и Арина', type: 'name'},
  {id: 'tonoyan-s', nameStr: 'Дорогая Тоноян Сусана', type: 'singleName'},
  {id: 'tonoyan-a', nameStr: 'Аркадий, Ася, Александр и Лев', type: 'name'},
  {id: 'gandilian', nameStr: 'Геворк, Галина, Рустам и Михаил', type: 'name'},
  {id: 'pogosov-s', nameStr: 'Погосова Серго', type: 'family'},
  {id: 'pogosov-a', nameStr: 'Погосова Анатолия', type: 'family'},
  {id: '33', nameStr: 'Сироповых', type: 'family'},
  {id: 'anushik-igor', nameStr: 'Анушик и Игорь', type: 'name'},
  {id: 'arutyunov', nameStr: 'Арутюновых', type: 'family'},
  {id: 'manukyan', nameStr: 'Манукян', type: 'family'},
  {id: 'tata', nameStr: 'Дорогая Татевик', type: 'singleName'},
  {id: 'nastya-kostya', nameStr: 'Настя и Костя', type: 'name'},
  {id: 'nadya', nameStr: 'Дорогая Надя', type: 'singleName'},
]
